export const SITE = {
  url: "https://monahukuk.com",
  name: "Mona Hukuk",
  legalName: "Mona Hukuk Bürosu",
  email: "info@monahukuk.com",
  phone: "+90 (242) 606 14 32",
  phoneE164: "+902426061432",
  city: "Antalya",
  region: "Antalya",
  country: "TR",
  countryName: "Türkiye",
  postalCode: "07050",
  geo: { latitude: 36.8841, longitude: 30.7056 },
  hours: { opens: "09:00", closes: "18:00", days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"] },
  founded: 2018,
  languages: ["tr", "en", "de", "ru", "ar"],
  social: [] as string[],
  ogImage: "/opengraph-image",
} as const;

export const KEYWORDS: Record<string, string[]> = {
  tr: [
    "Antalya hukuk bürosu",
    "Antalya avukat",
    "Antalya yabancılar avukatı",
    "Antalya yabancı danışmanlık",
    "Antalya göçmenlik avukatı",
    "Türkiye oturma izni avukatı",
    "Antalya gayrimenkul avukatı yabancı",
    "Antalya boşanma avukatı yabancı",
    "Türk vatandaşlığı avukatı",
    "KVKK avukatı Türkiye",
    "Antalya ticaret hukuku avukatı",
    "Antalya iş hukuku avukatı",
  ],
  en: [
    "law firm Antalya",
    "lawyer in Antalya",
    "lawyer for foreigners in Turkey",
    "English speaking lawyer Antalya",
    "Antalya immigration lawyer",
    "Turkish residence permit lawyer",
    "real estate lawyer Antalya foreigner",
    "divorce lawyer Antalya English",
    "Turkish citizenship lawyer",
    "KVKK GDPR Turkey lawyer",
    "commercial lawyer Turkey",
    "labor lawyer Antalya expat",
  ],
  de: [
    "Rechtsanwalt Antalya",
    "Anwalt für Ausländer Türkei",
    "Kanzlei Antalya Deutschsprachig",
    "Aufenthaltserlaubnis Türkei Anwalt",
    "Immobilienrecht Antalya Anwalt",
    "Türkische Staatsangehörigkeit Anwalt",
    "Scheidungsanwalt Antalya",
    "Türkei Arbeitsrecht Anwalt",
    "KVKK DSGVO Anwalt Türkei",
    "Handelsrecht Türkei Anwalt",
  ],
  ru: [
    "адвокат Анталья",
    "юрист для иностранцев Турция",
    "юридическая фирма Анталья",
    "вид на жительство в Турции адвокат",
    "недвижимость Турция юрист",
    "гражданство Турции адвокат",
    "развод в Турции адвокат",
    "трудовое право Турция адвокат",
    "коммерческое право Анталья",
    "KVKK GDPR адвокат Турция",
  ],
  ar: [
    "محامي أنطاليا",
    "محامي للأجانب في تركيا",
    "مكتب محاماة أنطاليا",
    "تصريح إقامة تركيا محامي",
    "عقارات تركيا محامي",
    "الجنسية التركية محامي",
    "طلاق في تركيا محامي",
    "قانون العمل تركيا محامي",
    "قانون تجاري تركيا",
    "KVKK محامي تركيا",
  ],
};
