export const SITE = {
  url: "https://monahukuk.com",
  name: "MONA HUKUK",
  legalName: "MONA HUKUK Bürosu",
  email: "contact@monahukuk.com",
  phone: "+90 (242) 606 14 32",
  phoneE164: "+902426061432",
  city: "Antalya",
  region: "Antalya",
  country: "TR",
  countryName: "Türkiye",
  postalCode: "07050",
  geo: { latitude: 36.8841, longitude: 30.7056 },
  hours: { opens: "09:00", closes: "18:00", days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"] },
  founded: 2018,
  languages: ["tr", "en", "de", "ru", "ar", "es", "fr"],
  // Google Business Profile ve sosyal medya URL'leri → sameAs schema sinyali
  social: [
    // "https://maps.app.goo.gl/XXXX",  // GBP linki buraya eklenecek
  ] as string[],
  ogImage: "/opengraph-image",
} as const;

export const KEYWORDS: Record<string, string[]> = {
  tr: [
    "Antalya hukuk bürosu",
    "Antalya avukat",
    "Antalya yabancılar avukatı",
    "Antalya yabancı danışmanlık",
    "Antalya göçmenlik avukatı",
    "Türkiye oturma izni avukatı",
    "Antalya gayrimenkul avukatı yabancı",
    "Antalya boşanma avukatı yabancı",
    "Türk vatandaşlığı avukatı",
    "KVKK avukatı Türkiye",
    "Antalya Ticaret Hukuku avukatı",
    "Antalya İş Hukuku avukatı",
  ],
  en: [
    "law firm Antalya",
    "lawyer in Antalya",
    "lawyer for foreigners in Turkey",
    "English speaking lawyer Antalya",
    "Antalya immigration lawyer",
    "Turkish residence permit lawyer",
    "real estate lawyer Antalya foreigner",
    "divorce lawyer Antalya English",
    "Turkish citizenship lawyer",
    "KVKK GDPR Turkey lawyer",
    "commercial lawyer Turkey",
    "labor lawyer Antalya expat",
  ],
  de: [
    "Rechtsanwalt Antalya",
    "Anwalt für Ausländer Türkei",
    "Kanzlei Antalya deutschsprachig",
    "Einwanderungsanwalt Antalya",
    "Aufenthaltserlaubnis Türkei Anwalt",
    "Immobilienrecht Antalya Anwalt",
    "Türkische Staatsangehörigkeit Anwalt",
    "Scheidungsanwalt Antalya",
    "Türkei Arbeitsrecht Anwalt",
    "KVKK DSGVO Anwalt Türkei",
    "Handelsrecht Türkei Anwalt",
    "Anwalt Türkei deutschsprachig",
  ],
  ru: [
    "адвокат Анталья",
    "юрист для иностранцев Турция",
    "юридическая фирма Анталья",
    "русскоязычный адвокат в Турции",
    "иммиграционный адвокат Анталья",
    "вид на жительство в Турции адвокат",
    "недвижимость Турция юрист",
    "гражданство Турции адвокат",
    "развод в Турции адвокат",
    "трудовое право Турция адвокат",
    "коммерческое право Анталья",
    "KVKK GDPR адвокат Турция",
  ],
  ar: [
    "محامي أنطاليا",
    "محامي للأجانب في تركيا",
    "مكتب محاماة أنطاليا",
    "محامي ناطق بالعربية في تركيا",
    "محامي الهجرة في تركيا",
    "تصريح إقامة تركيا محامي",
    "عقارات تركيا محامي",
    "الجنسية التركية محامي",
    "طلاق في تركيا محامي",
    "قانون العمل تركيا محامي",
    "قانون تجاري تركيا",
    "KVKK محامي تركيا",
  ],
  es: [
    "bufete de abogados Antalya",
    "abogado en Antalya",
    "abogado para extranjeros en Turquía",
    "abogado hispanohablante Antalya",
    "abogado de inmigración Turquía",
    "permiso de residencia Turquía abogado",
    "abogado inmobiliario Antalya extranjero",
    "ciudadanía turca abogado",
    "abogado divorcio Antalya",
    "derecho laboral Turquía abogado",
    "derecho mercantil Turquía",
    "KVKK RGPD abogado Turquía",
  ],
  fr: [
    "cabinet d'avocats Antalya",
    "avocat en Turquie",
    "avocat pour étrangers Turquie",
    "avocat francophone Antalya",
    "avocat immigration Turquie",
    "permis de séjour Turquie avocat",
    "avocat immobilier Antalya étranger",
    "nationalité turque avocat",
    "avocat divorce Antalya",
    "droit du travail Turquie avocat",
    "droit commercial Turquie avocat",
    "KVKK RGPD avocat Turquie",
  ],
};
