export const SITE = {
  url: "https://monahukuk.com",
  name: "Mona Hukuk",
  legalName: "Mona Hukuk Bürosu",
  email: "info@monahukuk.com",
  phone: "+90 (532) 390 05 10",
  phoneE164: "+905323900510",
  city: "Antalya",
  region: "Antalya",
  country: "TR",
  countryName: "Türkiye",
  postalCode: "07050",
  geo: { latitude: 36.8841, longitude: 30.7056 },
  hours: { opens: "09:00", closes: "18:00", days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"] },
  founded: 2018,
  languages: ["en", "tr"],
  social: [] as string[],
  ogImage: "/opengraph-image",
} as const;

export const KEYWORDS = {
  en: [
    "law firm Antalya",
    "lawyer in Antalya",
    "lawyer for foreigners in Turkey",
    "English speaking lawyer Antalya",
    "Antalya immigration lawyer",
    "Turkish residence permit lawyer",
    "real estate lawyer Antalya foreigner",
    "divorce lawyer Antalya English",
    "Turkish citizenship lawyer",
    "KVKK GDPR Turkey lawyer",
    "commercial lawyer Turkey",
    "labor lawyer Antalya expat",
  ],
  tr: [
    "Antalya hukuk bürosu",
    "Antalya avukat",
    "Antalya yabancılar avukatı",
    "Antalya İngilizce konuşan avukat",
    "Antalya göçmenlik avukatı",
    "Türkiye oturma izni avukatı",
    "Antalya gayrimenkul avukatı yabancı",
    "Antalya boşanma avukatı yabancı",
    "Türk vatandaşlığı avukatı",
    "KVKK GDPR avukatı Türkiye",
    "Antalya ticaret hukuku avukatı",
    "Antalya iş hukuku avukatı yabancı",
  ],
} as const;
