import type { NextConfig } from "next";
import createNextIntlPlugin from "next-intl/plugin";

const withNextIntl = createNextIntlPlugin("./src/i18n/request.ts");

const nextConfig: NextConfig = {
  reactStrictMode: true,
  staticPageGenerationTimeout: 180,
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "images.unsplash.com",
        pathname: "/**",
      },
    ],
  },
  async headers() {
    return [
      {
        source: "/:path*/opengraph-image",
        headers: [{ key: "X-Robots-Tag", value: "noindex, nofollow" }],
      },
    ];
  },
  async redirects() {
    return [
      // ── Locale prefix'siz statik sayfalar → TR (defaultLocale) ──────────────
      // Google eski dış linklerden veya eski sitemap'tan bu URL'leri taradı.
      // next-intl localePrefix:"always" kullandığından bunlar 404 döndürüyor.
      { source: "/contact", destination: "/tr/contact", permanent: true },
      { source: "/team", destination: "/tr/team", permanent: true },
      { source: "/about", destination: "/tr/about", permanent: true },
      { source: "/practice-areas", destination: "/tr/practice-areas", permanent: true },
      { source: "/articles", destination: "/tr/articles", permanent: true },
      // EN-slug makaleler prefix'siz erişimlerde → EN locale
      // (catch-all aşağıdaki kural öncesinde bu spesifik slug'ları yakalamalı)
      { source: "/articles/eviction-landlord-need-turkey", destination: "/en/articles/eviction-landlord-need-turkey", permanent: true },
      // Locale prefix'siz makale slug'ları — spesifik kurallar önce, catch-all sonda
      { source: "/articles/severance-notice-pay-foreigners-calculation", destination: "/en/articles/severance-notice-pay-foreigners-calculation", permanent: true },
      { source: "/articles/short-term-residence-permit-turkey-guide", destination: "/en/articles/short-term-residence-permit-turkey-guide", permanent: true },
      { source: "/articles/investment-property-turkey-tax-legal-obligations", destination: "/en/articles/investment-property-turkey-tax-legal-obligations", permanent: true },
      { source: "/articles/common-mistakes-commercial-contracts-turkey", destination: "/en/articles/common-mistakes-commercial-contracts-turkey", permanent: true },
      { source: "/articles/family-residence-permit-spouse-turkish-citizen", destination: "/en/articles/family-residence-permit-spouse-turkish-citizen", permanent: true },
      { source: "/articles/cybercrime-charges-foreigners-turkey", destination: "/en/articles/cybercrime-charges-foreigners-turkey", permanent: true },
      { source: "/articles/ogrenci-ikamet-izninden-calisma-izni-gecis", destination: "/tr/articles/ogrenci-ikamet-izninden-calisma-izni-gecis", permanent: true },
      // Catch-all: locale'siz İngilizce slug → EN
      { source: "/articles/:slug+", destination: "/en/articles/:slug+", permanent: true },

      // ── TR locale'de İngilizce slug → doğru Türkçe slug ───────────────────────
      { source: "/tr/articles/family-residence-permit-spouse-turkish-citizen", destination: "/tr/articles/aile-ikamet-izni-turk-vatandasi-es", permanent: true },
      { source: "/tr/articles/work-permit-denial-appeal-turkey", destination: "/tr/articles/calisma-izni-reddi-itiraz-yollari", permanent: true },
      { source: "/tr/articles/short-term-residence-permit-turkey-guide", destination: "/tr/articles/turkiye-kisa-donem-ikamet-izni-basvurusu-rehberi", permanent: true },
      { source: "/tr/articles/narcotics-offences-defence-strategies-turkey", destination: "/tr/articles/uyusturucu-suclarinda-savunma-stratejileri", permanent: true },
      { source: "/tr/articles/restriction-code-check-removal-foreigners", destination: "/tr/articles/tahdit-kodu-sorgulama-kaldirma", permanent: true },
      { source: "/tr/articles/foreign-employee-termination-turkey", destination: "/tr/articles/turkiyede-yabanci-calisanin-isten-cikarilmasi", permanent: true },

      // ── Yanlış locale'de TR slug'larına erişim → doğru locale + İngilizce slug ─
      { source: "/ar/articles/miras-reddi-sartlar-sure", destination: "/ar/articles/inheritance-rejection-conditions-period", permanent: true },
      { source: "/ar/articles/anonim-sirket-vs-limited-sirket-secim", destination: "/ar/articles/jsc-vs-llc-which-to-choose-turkey", permanent: true },
      { source: "/ar/articles/ogrenci-ikamet-izninden-calisma-izni-gecis", destination: "/ar/articles/student-to-work-permit-transition-turkey", permanent: true },
      { source: "/ar/articles/vasiyetname-duzenleme-yabancilar-icin", destination: "/ar/articles/will-drafting-foreigners-turkey", permanent: true },
      { source: "/ar/articles/yapay-zeka-turk-hukuku-duzenleme-cercevesi", destination: "/ar/articles/artificial-intelligence-turkish-law-framework", permanent: true },
      { source: "/ar/articles/yabanci-es-cocuk-icin-turk-vatandasligi", destination: "/ar/articles/turkish-citizenship-for-spouse-and-children", permanent: true },
      { source: "/ar/articles/kvkk-uyumu-turkiye-veri-koruma-yukumlulukleri", destination: "/ar/articles/kvkk-compliance-turkey-data-protection", permanent: true },
      { source: "/ar/articles/eticaret-kvkk-cerez-politikasi", destination: "/ar/articles/ecommerce-kvkk-cookie-policy-compliance", permanent: true },
      { source: "/ar/articles/uzaktan-calisan-yabanci-isci-haklari", destination: "/ar/articles/remote-foreign-workers-rights-turkey", permanent: true },
      { source: "/ar/articles/trafik-kazasinda-ceza-sorumlulugu-yabanci-surucu", destination: "/ar/articles/traffic-accident-criminal-liability-foreign-drivers", permanent: true },
      { source: "/ar/articles/trafik-kazasinda-ceza-sorumlu-ugu-yabanci-surucu", destination: "/ar/articles/traffic-accident-criminal-liability-foreign-drivers", permanent: true },
      { source: "/de/articles/miras-reddi-sartlar-sure", destination: "/de/articles/inheritance-rejection-conditions-period", permanent: true },
      { source: "/de/articles/vize-reddi-iptal-davasi", destination: "/de/articles/visa-denial-cancellation-lawsuit-turkey", permanent: true },
      { source: "/de/articles/ogrenci-ikamet-izninden-calisma-izni-gecis", destination: "/de/articles/student-to-work-permit-transition-turkey", permanent: true },
      { source: "/de/articles/eticaret-kvkk-cerez-politikasi", destination: "/de/articles/ecommerce-kvkk-cookie-policy-compliance", permanent: true },
      { source: "/de/articles/antalya-kira-sozlesmesi-haklar-yukumlulukler", destination: "/de/articles/antalya-rental-agreement-rights-obligations", permanent: true },
      { source: "/de/articles/sahte-tapu-dolandiriciligina-karsi-korunma", destination: "/de/articles/protecting-against-fraud-property-purchase-turkey", permanent: true },
      { source: "/de/articles/kvkk-uyumu-turkiye-veri-koruma-yukumlulukleri", destination: "/de/articles/kvkk-compliance-turkey-data-protection", permanent: true },
      { source: "/en/articles/tahdit-kodu-sorgulama-kaldirma", destination: "/en/articles/restriction-code-check-removal-foreigners", permanent: true },
      { source: "/en/articles/yazilim-lisans-sozlesmelerinde-hukuki-riskler", destination: "/en/articles/software-license-agreements-legal-risks", permanent: true },
      { source: "/en/articles/sirket-devir-birlesme-hukuki-surec", destination: "/en/articles/company-merger-acquisition-legal-process", permanent: true },
      { source: "/en/articles/belediye-cezalarina-itiraz-yabancilar", destination: "/en/articles/municipality-fines-objection-foreigners", permanent: true },
      { source: "/en/articles/sinir-disi-karari-itiraz-hak-yollari", destination: "/en/articles/deportation-order-appeal-turkey", permanent: true },
      { source: "/en/articles/yabanci-sermaye-turkiyede-ortaklik-kurma", destination: "/en/articles/foreign-capital-partnership-turkey", permanent: true },
      { source: "/ru/articles/anonim-sirket-vs-limited-sirket-secim", destination: "/ru/articles/jsc-vs-llc-which-to-choose-turkey", permanent: true },
      { source: "/ru/articles/velayet-davalarinda-yabancilarin-haklari", destination: "/ru/articles/custody-rights-foreign-clients-turkey", permanent: true },
      { source: "/ru/articles/dolandiricilik-magdurlari-icin-hukuki-yollar", destination: "/ru/articles/fraud-victims-foreigners-legal-remedies", permanent: true },
      { source: "/ru/articles/yabancilar-icin-idare-mahkemesi-surecleri", destination: "/ru/articles/administrative-court-procedure-foreigners", permanent: true },

      // ── hukuki-haberler → legal-news (3 Mayıs'ta route rename edildi) ────────
      { source: "/tr/hukuki-haberler", destination: "/tr/legal-news", permanent: true },
      { source: "/en/hukuki-haberler", destination: "/en/legal-news", permanent: true },
      { source: "/de/hukuki-haberler", destination: "/de/legal-news", permanent: true },
      { source: "/ru/hukuki-haberler", destination: "/ru/legal-news", permanent: true },
      { source: "/ar/hukuki-haberler", destination: "/ar/legal-news", permanent: true },
      { source: "/es/hukuki-haberler", destination: "/es/legal-news", permanent: true },
      { source: "/fr/hukuki-haberler", destination: "/fr/legal-news", permanent: true },
      { source: "/tr/hukuki-haberler/:slug+", destination: "/tr/legal-news/:slug+", permanent: true },
      { source: "/en/hukuki-haberler/:slug+", destination: "/en/legal-news/:slug+", permanent: true },
      { source: "/de/hukuki-haberler/:slug+", destination: "/de/legal-news/:slug+", permanent: true },
      { source: "/ru/hukuki-haberler/:slug+", destination: "/ru/legal-news/:slug+", permanent: true },
      { source: "/ar/hukuki-haberler/:slug+", destination: "/ar/legal-news/:slug+", permanent: true },
      { source: "/es/hukuki-haberler/:slug+", destination: "/es/legal-news/:slug+", permanent: true },
      { source: "/fr/hukuki-haberler/:slug+", destination: "/fr/legal-news/:slug+", permanent: true },

      // ── DE: Türkçe-slug → İngilizce-slug (Google tarafından indexlenmiş eski URL'ler) ─
      { source: "/de/articles/aile-ikamet-izni-turk-vatandasi-es", destination: "/de/articles/family-residence-permit-spouse-turkish-citizen", permanent: true },
      { source: "/de/articles/anonim-sirket-vs-limited-sirket-secim", destination: "/de/articles/jsc-vs-llc-which-to-choose-turkey", permanent: true },
      { source: "/de/articles/belediye-cezalarina-itiraz-yabancilar", destination: "/de/articles/municipality-fines-objection-foreigners", permanent: true },
      { source: "/de/articles/calisma-izni-iptali-is-sozlesmesi-sona-ermesi", destination: "/de/articles/work-permit-cancellation-employment-contract-end", permanent: true },
      { source: "/de/articles/calisma-izni-reddi-itiraz-yollari", destination: "/de/articles/work-permit-denial-appeal-turkey", permanent: true },
      { source: "/de/articles/dolandiricilik-magdurlari-icin-hukuki-yollar", destination: "/de/articles/fraud-victims-foreigners-legal-remedies", permanent: true },
      { source: "/de/articles/evlilik-yoluyla-turk-vatandasligi", destination: "/de/articles/turkish-citizenship-through-marriage", permanent: true },
      { source: "/de/articles/ihtiyac-nedeniyle-tahliye-tbk-350", destination: "/de/articles/eviction-landlord-need-turkey", permanent: true },
      { source: "/de/articles/iki-hakli-ihtar-kira-odemeyen-kiraciyi-tahliye", destination: "/de/articles/tenant-non-payment-eviction-two-notice-turkey", permanent: true },
      { source: "/de/articles/isyeri-kira-sozlesmesi", destination: "/de/articles/commercial-lease-turkey", permanent: true },
      { source: "/de/articles/kidem-ihbar-tazminati-yabancilar-hesaplama", destination: "/de/articles/severance-notice-pay-foreigners-calculation", permanent: true },
      { source: "/de/articles/kira-artisi-siniri-tbk-344", destination: "/de/articles/rent-increase-cap-turkey", permanent: true },
      { source: "/de/articles/kira-depozito-guvence-bedeli", destination: "/de/articles/security-deposit-rental-turkey", permanent: true },
      { source: "/de/articles/kira-tespiti-davasi", destination: "/de/articles/rent-determination-lawsuit-turkey", permanent: true },
      { source: "/de/articles/miras-reddi-sartlar-sure", destination: "/de/articles/inheritance-rejection-conditions-period", permanent: true },
      { source: "/de/articles/mobbing-hukuki-yaptirim", destination: "/de/articles/mobbing-workplace-harassment-legal-remedies", permanent: true },
      { source: "/de/articles/nafaka-turleri-yabanci-muvekkiller", destination: "/de/articles/alimony-types-foreign-clients-turkey", permanent: true },
      { source: "/de/articles/oturma-izni-iptali-hukuki-yollar", destination: "/de/articles/residence-permit-cancellation-legal-routes", permanent: true },
      { source: "/de/articles/sinir-disi-karari-itiraz-hak-yollari", destination: "/de/articles/deportation-order-appeal-turkey", permanent: true },
      { source: "/de/articles/sirket-devir-birlesme-hukuki-surec", destination: "/de/articles/company-merger-acquisition-legal-process", permanent: true },
      { source: "/de/articles/sosyal-medya-iftirasi-hukuki-yaptirim", destination: "/de/articles/social-media-defamation-legal-remedies", permanent: true },
      { source: "/de/articles/tahdit-kodu-sorgulama-kaldirma", destination: "/de/articles/restriction-code-check-removal-foreigners", permanent: true },
      { source: "/de/articles/tapu-devri-sirasinda-dikkat-edilmesi-gerekenler", destination: "/de/articles/title-deed-transfer-checklist-foreign-buyers", permanent: true },
      { source: "/de/articles/ticari-sozlesmelerde-sikca-yapilan-hatalar", destination: "/de/articles/common-mistakes-commercial-contracts-turkey", permanent: true },
      { source: "/de/articles/trafik-kazasinda-ceza-sorumlulugu-yabanci-surucu", destination: "/de/articles/traffic-accident-criminal-liability-foreign-drivers", permanent: true },
      { source: "/de/articles/turk-vatandasligi-basvuru-reddi-itiraz", destination: "/de/articles/turkish-citizenship-application-rejection-appeal", permanent: true },
      { source: "/de/articles/turk-vatandasligi-cifte-vatandaslik-statusu", destination: "/de/articles/turkish-dual-citizenship-status", permanent: true },
      { source: "/de/articles/turkiye-kisa-donem-ikamet-izni-basvurusu-rehberi", destination: "/de/articles/short-term-residence-permit-turkey-guide", permanent: true },
      { source: "/de/articles/turkiyede-mulku-olan-yabancilarin-miras-hukuku", destination: "/de/articles/foreigners-property-turkey-inheritance-law", permanent: true },
      { source: "/de/articles/turkiyede-yabanci-calisanin-isten-cikarilmasi", destination: "/de/articles/foreign-employee-termination-turkey", permanent: true },
      { source: "/de/articles/uluslararasi-bosanma-turkiyede-tanima-tenfiz", destination: "/de/articles/international-divorce-recognition-enforcement-turkey", permanent: true },
      { source: "/de/articles/uluslararasi-cocuk-kacirma-lahey-sozlesmesi", destination: "/de/articles/international-child-abduction-hague-convention", permanent: true },
      { source: "/de/articles/uyusturucu-suclarinda-savunma-stratejileri", destination: "/de/articles/narcotics-offences-defence-strategies-turkey", permanent: true },
      { source: "/de/articles/uzaktan-calisan-yabanci-isci-haklari", destination: "/de/articles/remote-foreign-workers-rights-turkey", permanent: true },
      { source: "/de/articles/vasiyetname-duzenleme-yabancilar-icin", destination: "/de/articles/will-drafting-foreigners-turkey", permanent: true },
      { source: "/de/articles/velayet-davalarinda-yabancilarin-haklari", destination: "/de/articles/custody-rights-foreign-clients-turkey", permanent: true },
      { source: "/de/articles/veraset-ilami-yabanci-mirasci-rehber", destination: "/de/articles/certificate-of-inheritance-foreign-heirs", permanent: true },
      { source: "/de/articles/yabanci-es-cocuk-icin-turk-vatandasligi", destination: "/de/articles/turkish-citizenship-for-spouse-and-children", permanent: true },
      { source: "/de/articles/yabanci-eslerin-bosanmasinda-mal-paylasimi", destination: "/de/articles/property-division-foreign-spouses-divorce-turkey", permanent: true },
      { source: "/de/articles/yabanci-olarak-turkiye-daire-almak-hukuki-rehber", destination: "/de/articles/buying-property-in-turkey-foreigner-guide", permanent: true },
      { source: "/de/articles/yabanci-sermaye-turkiyede-ortaklik-kurma", destination: "/de/articles/foreign-capital-partnership-turkey", permanent: true },
      { source: "/de/articles/yabanci-sermayesi-turkiyede-sirket-kurma", destination: "/de/articles/foreign-investor-company-formation-turkey", permanent: true },
      { source: "/de/articles/yabanci-vasiyetnamesi-turkiyede-tanima", destination: "/de/articles/foreign-will-recognition-turkey", permanent: true },
      { source: "/de/articles/yabanci-yatirimci-turkiyede-sirket-kurma", destination: "/de/articles/foreign-investor-company-formation-turkey", permanent: true },
      { source: "/de/articles/yabancilar-icin-idare-mahkemesi-surecleri", destination: "/de/articles/administrative-court-procedure-foreigners", permanent: true },
      { source: "/de/articles/yabancilar-icin-turkiye-ceza-davasi-sureci", destination: "/de/articles/criminal-procedure-foreigners-turkey", permanent: true },
      { source: "/de/articles/yabancilar-icin-tutuklama-adli-kontrol", destination: "/de/articles/detention-judicial-control-foreigners-turkey", permanent: true },
      { source: "/de/articles/yapay-zeka-turk-hukuku-duzenleme-cercevesi", destination: "/de/articles/artificial-intelligence-turkish-law-framework", permanent: true },
      { source: "/de/articles/yatirim-amacli-konut-alimi-vergi-hukuki-yukumluluk", destination: "/de/articles/investment-property-turkey-tax-legal-obligations", permanent: true },
      { source: "/de/articles/yatirim-yoluyla-turk-vatandasligi-tam-rehber", destination: "/de/articles/turkish-citizenship-by-investment-full-guide", permanent: true },
      { source: "/de/articles/yazilim-lisans-sozlesmelerinde-hukuki-riskler", destination: "/de/articles/software-license-agreements-legal-risks", permanent: true },

      // ── RU: Türkçe-slug → İngilizce-slug ─────────────────────────────────────
      { source: "/ru/articles/aile-ikamet-izni-turk-vatandasi-es", destination: "/ru/articles/family-residence-permit-spouse-turkish-citizen", permanent: true },
      { source: "/ru/articles/antalya-kira-sozlesmesi-haklar-yukumlulukler", destination: "/ru/articles/antalya-rental-agreement-rights-obligations", permanent: true },
      { source: "/ru/articles/belediye-cezalarina-itiraz-yabancilar", destination: "/ru/articles/municipality-fines-objection-foreigners", permanent: true },
      { source: "/ru/articles/calisma-izni-iptali-is-sozlesmesi-sona-ermesi", destination: "/ru/articles/work-permit-cancellation-employment-contract-end", permanent: true },
      { source: "/ru/articles/calisma-izni-reddi-itiraz-yollari", destination: "/ru/articles/work-permit-denial-appeal-turkey", permanent: true },
      { source: "/ru/articles/eticaret-kvkk-cerez-politikasi", destination: "/ru/articles/ecommerce-kvkk-cookie-policy-compliance", permanent: true },
      { source: "/ru/articles/evlilik-yoluyla-turk-vatandasligi", destination: "/ru/articles/turkish-citizenship-through-marriage", permanent: true },
      { source: "/ru/articles/ihtiyac-nedeniyle-tahliye-tbk-350", destination: "/ru/articles/eviction-landlord-need-turkey", permanent: true },
      { source: "/ru/articles/iki-hakli-ihtar-kira-odemeyen-kiraciyi-tahliye", destination: "/ru/articles/tenant-non-payment-eviction-two-notice-turkey", permanent: true },
      { source: "/ru/articles/isyeri-kira-sozlesmesi", destination: "/ru/articles/commercial-lease-turkey", permanent: true },
      { source: "/ru/articles/kidem-ihbar-tazminati-yabancilar-hesaplama", destination: "/ru/articles/severance-notice-pay-foreigners-calculation", permanent: true },
      { source: "/ru/articles/kira-artisi-siniri-tbk-344", destination: "/ru/articles/rent-increase-cap-turkey", permanent: true },
      { source: "/ru/articles/kira-depozito-guvence-bedeli", destination: "/ru/articles/security-deposit-rental-turkey", permanent: true },
      { source: "/ru/articles/kira-tespiti-davasi", destination: "/ru/articles/rent-determination-lawsuit-turkey", permanent: true },
      { source: "/ru/articles/kvkk-uyumu-turkiye-veri-koruma-yukumlulukleri", destination: "/ru/articles/kvkk-compliance-turkey-data-protection", permanent: true },
      { source: "/ru/articles/miras-reddi-sartlar-sure", destination: "/ru/articles/inheritance-rejection-conditions-period", permanent: true },
      { source: "/ru/articles/mobbing-hukuki-yaptirim", destination: "/ru/articles/mobbing-workplace-harassment-legal-remedies", permanent: true },
      { source: "/ru/articles/nafaka-turleri-yabanci-muvekkiller", destination: "/ru/articles/alimony-types-foreign-clients-turkey", permanent: true },
      { source: "/ru/articles/ogrenci-ikamet-izninden-calisma-izni-gecis", destination: "/ru/articles/student-to-work-permit-transition-turkey", permanent: true },
      { source: "/ru/articles/oturma-izni-iptali-hukuki-yollar", destination: "/ru/articles/residence-permit-cancellation-legal-routes", permanent: true },
      { source: "/ru/articles/sahte-tapu-dolandiriciligina-karsi-korunma", destination: "/ru/articles/protecting-against-fraud-property-purchase-turkey", permanent: true },
      { source: "/ru/articles/sinir-disi-karari-itiraz-hak-yollari", destination: "/ru/articles/deportation-order-appeal-turkey", permanent: true },
      { source: "/ru/articles/sirket-devir-birlesme-hukuki-surec", destination: "/ru/articles/company-merger-acquisition-legal-process", permanent: true },
      { source: "/ru/articles/sosyal-medya-iftirasi-hukuki-yaptirim", destination: "/ru/articles/social-media-defamation-legal-remedies", permanent: true },
      { source: "/ru/articles/tahdit-kodu-sorgulama-kaldirma", destination: "/ru/articles/restriction-code-check-removal-foreigners", permanent: true },
      { source: "/ru/articles/tapu-devri-sirasinda-dikkat-edilmesi-gerekenler", destination: "/ru/articles/title-deed-transfer-checklist-foreign-buyers", permanent: true },
      { source: "/ru/articles/ticari-sozlesmelerde-sikca-yapilan-hatalar", destination: "/ru/articles/common-mistakes-commercial-contracts-turkey", permanent: true },
      { source: "/ru/articles/trafik-kazasinda-ceza-sorumlulugu-yabanci-surucu", destination: "/ru/articles/traffic-accident-criminal-liability-foreign-drivers", permanent: true },
      { source: "/ru/articles/turk-vatandasligi-basvuru-reddi-itiraz", destination: "/ru/articles/turkish-citizenship-application-rejection-appeal", permanent: true },
      { source: "/ru/articles/turk-vatandasligi-cifte-vatandaslik-statusu", destination: "/ru/articles/turkish-dual-citizenship-status", permanent: true },
      { source: "/ru/articles/turkiye-kisa-donem-ikamet-izni-basvurusu-rehberi", destination: "/ru/articles/short-term-residence-permit-turkey-guide", permanent: true },
      { source: "/ru/articles/turkiyede-mulku-olan-yabancilarin-miras-hukuku", destination: "/ru/articles/foreigners-property-turkey-inheritance-law", permanent: true },
      { source: "/ru/articles/turkiyede-yabanci-calisanin-isten-cikarilmasi", destination: "/ru/articles/foreign-employee-termination-turkey", permanent: true },
      { source: "/ru/articles/uluslararasi-bosanma-turkiyede-tanima-tenfiz", destination: "/ru/articles/international-divorce-recognition-enforcement-turkey", permanent: true },
      { source: "/ru/articles/uluslararasi-cocuk-kacirma-lahey-sozlesmesi", destination: "/ru/articles/international-child-abduction-hague-convention", permanent: true },
      { source: "/ru/articles/uyusturucu-suclarinda-savunma-stratejileri", destination: "/ru/articles/narcotics-offences-defence-strategies-turkey", permanent: true },
      { source: "/ru/articles/uzaktan-calisan-yabanci-isci-haklari", destination: "/ru/articles/remote-foreign-workers-rights-turkey", permanent: true },
      { source: "/ru/articles/vasiyetname-duzenleme-yabancilar-icin", destination: "/ru/articles/will-drafting-foreigners-turkey", permanent: true },
      { source: "/ru/articles/veraset-ilami-yabanci-mirasci-rehber", destination: "/ru/articles/certificate-of-inheritance-foreign-heirs", permanent: true },
      { source: "/ru/articles/vize-reddi-iptal-davasi", destination: "/ru/articles/visa-denial-cancellation-lawsuit-turkey", permanent: true },
      { source: "/ru/articles/yabanci-es-cocuk-icin-turk-vatandasligi", destination: "/ru/articles/turkish-citizenship-for-spouse-and-children", permanent: true },
      { source: "/ru/articles/yabanci-eslerin-bosanmasinda-mal-paylasimi", destination: "/ru/articles/property-division-foreign-spouses-divorce-turkey", permanent: true },
      { source: "/ru/articles/yabanci-olarak-turkiye-daire-almak-hukuki-rehber", destination: "/ru/articles/buying-property-in-turkey-foreigner-guide", permanent: true },
      { source: "/ru/articles/yabanci-sermaye-turkiyede-ortaklik-kurma", destination: "/ru/articles/foreign-capital-partnership-turkey", permanent: true },
      { source: "/ru/articles/yabanci-vasiyetnamesi-turkiyede-tanima", destination: "/ru/articles/foreign-will-recognition-turkey", permanent: true },
      { source: "/ru/articles/yabanci-yatirimci-turkiyede-sirket-kurma", destination: "/ru/articles/foreign-investor-company-formation-turkey", permanent: true },
      { source: "/ru/articles/yabancilar-icin-turkiye-ceza-davasi-sureci", destination: "/ru/articles/criminal-procedure-foreigners-turkey", permanent: true },
      { source: "/ru/articles/yabancilar-icin-tutuklama-adli-kontrol", destination: "/ru/articles/detention-judicial-control-foreigners-turkey", permanent: true },
      { source: "/ru/articles/yapay-zeka-turk-hukuku-duzenleme-cercevesi", destination: "/ru/articles/artificial-intelligence-turkish-law-framework", permanent: true },
      { source: "/ru/articles/yatirim-amacli-konut-alimi-vergi-hukuki-yukumluluk", destination: "/ru/articles/investment-property-turkey-tax-legal-obligations", permanent: true },
      { source: "/ru/articles/yatirim-yoluyla-turk-vatandasligi-tam-rehber", destination: "/ru/articles/turkish-citizenship-by-investment-full-guide", permanent: true },
      { source: "/ru/articles/yazilim-lisans-sozlesmelerinde-hukuki-riskler", destination: "/ru/articles/software-license-agreements-legal-risks", permanent: true },

      // ── AR: Türkçe-slug → İngilizce-slug ─────────────────────────────────────
      { source: "/ar/articles/aile-ikamet-izni-turk-vatandasi-es", destination: "/ar/articles/family-residence-permit-spouse-turkish-citizen", permanent: true },
      { source: "/ar/articles/antalya-kira-sozlesmesi-haklar-yukumlulukler", destination: "/ar/articles/antalya-rental-agreement-rights-obligations", permanent: true },
      { source: "/ar/articles/belediye-cezalarina-itiraz-yabancilar", destination: "/ar/articles/municipality-fines-objection-foreigners", permanent: true },
      { source: "/ar/articles/calisma-izni-iptali-is-sozlesmesi-sona-ermesi", destination: "/ar/articles/work-permit-cancellation-employment-contract-end", permanent: true },
      { source: "/ar/articles/calisma-izni-reddi-itiraz-yollari", destination: "/ar/articles/work-permit-denial-appeal-turkey", permanent: true },
      { source: "/ar/articles/dolandiricilik-magdurlari-icin-hukuki-yollar", destination: "/ar/articles/fraud-victims-foreigners-legal-remedies", permanent: true },
      { source: "/ar/articles/evlilik-yoluyla-turk-vatandasligi", destination: "/ar/articles/turkish-citizenship-through-marriage", permanent: true },
      { source: "/ar/articles/ihtiyac-nedeniyle-tahliye-tbk-350", destination: "/ar/articles/eviction-landlord-need-turkey", permanent: true },
      { source: "/ar/articles/iki-hakli-ihtar-kira-odemeyen-kiraciyi-tahliye", destination: "/ar/articles/tenant-non-payment-eviction-two-notice-turkey", permanent: true },
      { source: "/ar/articles/isyeri-kira-sozlesmesi", destination: "/ar/articles/commercial-lease-turkey", permanent: true },
      { source: "/ar/articles/kidem-ihbar-tazminati-yabancilar-hesaplama", destination: "/ar/articles/severance-notice-pay-foreigners-calculation", permanent: true },
      { source: "/ar/articles/kira-artisi-siniri-tbk-344", destination: "/ar/articles/rent-increase-cap-turkey", permanent: true },
      { source: "/ar/articles/kira-depozito-guvence-bedeli", destination: "/ar/articles/security-deposit-rental-turkey", permanent: true },
      { source: "/ar/articles/kira-tespiti-davasi", destination: "/ar/articles/rent-determination-lawsuit-turkey", permanent: true },
      { source: "/ar/articles/mobbing-hukuki-yaptirim", destination: "/ar/articles/mobbing-workplace-harassment-legal-remedies", permanent: true },
      { source: "/ar/articles/nafaka-turleri-yabanci-muvekkiller", destination: "/ar/articles/alimony-types-foreign-clients-turkey", permanent: true },
      { source: "/ar/articles/oturma-izni-iptali-hukuki-yollar", destination: "/ar/articles/residence-permit-cancellation-legal-routes", permanent: true },
      { source: "/ar/articles/sahte-tapu-dolandiriciligina-karsi-korunma", destination: "/ar/articles/protecting-against-fraud-property-purchase-turkey", permanent: true },
      { source: "/ar/articles/sinir-disi-karari-itiraz-hak-yollari", destination: "/ar/articles/deportation-order-appeal-turkey", permanent: true },
      { source: "/ar/articles/sirket-devir-birlesme-hukuki-surec", destination: "/ar/articles/company-merger-acquisition-legal-process", permanent: true },
      { source: "/ar/articles/sosyal-medya-iftirasi-hukuki-yaptirim", destination: "/ar/articles/social-media-defamation-legal-remedies", permanent: true },
      { source: "/ar/articles/tahdit-kodu-sorgulama-kaldirma", destination: "/ar/articles/restriction-code-check-removal-foreigners", permanent: true },
      { source: "/ar/articles/tapu-devri-sirasinda-dikkat-edilmesi-gerekenler", destination: "/ar/articles/title-deed-transfer-checklist-foreign-buyers", permanent: true },
      { source: "/ar/articles/ticari-sozlesmelerde-sikca-yapilan-hatalar", destination: "/ar/articles/common-mistakes-commercial-contracts-turkey", permanent: true },
      { source: "/ar/articles/turk-vatandasligi-basvuru-reddi-itiraz", destination: "/ar/articles/turkish-citizenship-application-rejection-appeal", permanent: true },
      { source: "/ar/articles/turk-vatandasligi-cifte-vatandaslik-statusu", destination: "/ar/articles/turkish-dual-citizenship-status", permanent: true },
      { source: "/ar/articles/turkiye-kisa-donem-ikamet-izni-basvurusu-rehberi", destination: "/ar/articles/short-term-residence-permit-turkey-guide", permanent: true },
      { source: "/ar/articles/turkiyede-mulku-olan-yabancilarin-miras-hukuku", destination: "/ar/articles/foreigners-property-turkey-inheritance-law", permanent: true },
      { source: "/ar/articles/turkiyede-yabanci-calisanin-isten-cikarilmasi", destination: "/ar/articles/foreign-employee-termination-turkey", permanent: true },
      { source: "/ar/articles/uluslararasi-bosanma-turkiyede-tanima-tenfiz", destination: "/ar/articles/international-divorce-recognition-enforcement-turkey", permanent: true },
      { source: "/ar/articles/uluslararasi-cocuk-kacirma-lahey-sozlesmesi", destination: "/ar/articles/international-child-abduction-hague-convention", permanent: true },
      { source: "/ar/articles/uyusturucu-suclarinda-savunma-stratejileri", destination: "/ar/articles/narcotics-offences-defence-strategies-turkey", permanent: true },
      { source: "/ar/articles/velayet-davalarinda-yabancilarin-haklari", destination: "/ar/articles/custody-rights-foreign-clients-turkey", permanent: true },
      { source: "/ar/articles/veraset-ilami-yabanci-mirasci-rehber", destination: "/ar/articles/certificate-of-inheritance-foreign-heirs", permanent: true },
      { source: "/ar/articles/vize-reddi-iptal-davasi", destination: "/ar/articles/visa-denial-cancellation-lawsuit-turkey", permanent: true },
      { source: "/ar/articles/yabanci-eslerin-bosanmasinda-mal-paylasimi", destination: "/ar/articles/property-division-foreign-spouses-divorce-turkey", permanent: true },
      { source: "/ar/articles/yabanci-olarak-turkiye-daire-almak-hukuki-rehber", destination: "/ar/articles/buying-property-in-turkey-foreigner-guide", permanent: true },
      { source: "/ar/articles/yabanci-sermaye-turkiyede-ortaklik-kurma", destination: "/ar/articles/foreign-capital-partnership-turkey", permanent: true },
      { source: "/ar/articles/yabanci-vasiyetnamesi-turkiyede-tanima", destination: "/ar/articles/foreign-will-recognition-turkey", permanent: true },
      { source: "/ar/articles/yabanci-yatirimci-turkiyede-sirket-kurma", destination: "/ar/articles/foreign-investor-company-formation-turkey", permanent: true },
      { source: "/ar/articles/yabancilar-icin-idare-mahkemesi-surecleri", destination: "/ar/articles/administrative-court-procedure-foreigners", permanent: true },
      { source: "/ar/articles/yabancilar-icin-turkiye-ceza-davasi-sureci", destination: "/ar/articles/criminal-procedure-foreigners-turkey", permanent: true },
      { source: "/ar/articles/yabancilar-icin-tutuklama-adli-kontrol", destination: "/ar/articles/detention-judicial-control-foreigners-turkey", permanent: true },
      { source: "/ar/articles/yatirim-amacli-konut-alimi-vergi-hukuki-yukumluluk", destination: "/ar/articles/investment-property-turkey-tax-legal-obligations", permanent: true },
      { source: "/ar/articles/yatirim-yoluyla-turk-vatandasligi-tam-rehber", destination: "/ar/articles/turkish-citizenship-by-investment-full-guide", permanent: true },
      { source: "/ar/articles/yazilim-lisans-sozlesmelerinde-hukuki-riskler", destination: "/ar/articles/software-license-agreements-legal-risks", permanent: true },

      // ── ES: Türkçe-slug → İngilizce-slug ─────────────────────────────────────
      { source: "/es/articles/aile-ikamet-izni-turk-vatandasi-es", destination: "/es/articles/family-residence-permit-spouse-turkish-citizen", permanent: true },
      { source: "/es/articles/anonim-sirket-vs-limited-sirket-secim", destination: "/es/articles/jsc-vs-llc-which-to-choose-turkey", permanent: true },
      { source: "/es/articles/antalya-kira-sozlesmesi-haklar-yukumlulukler", destination: "/es/articles/antalya-rental-agreement-rights-obligations", permanent: true },
      { source: "/es/articles/belediye-cezalarina-itiraz-yabancilar", destination: "/es/articles/municipality-fines-objection-foreigners", permanent: true },
      { source: "/es/articles/calisma-izni-iptali-is-sozlesmesi-sona-ermesi", destination: "/es/articles/work-permit-cancellation-employment-contract-end", permanent: true },
      { source: "/es/articles/calisma-izni-reddi-itiraz-yollari", destination: "/es/articles/work-permit-denial-appeal-turkey", permanent: true },
      { source: "/es/articles/dolandiricilik-magdurlari-icin-hukuki-yollar", destination: "/es/articles/fraud-victims-foreigners-legal-remedies", permanent: true },
      { source: "/es/articles/eticaret-kvkk-cerez-politikasi", destination: "/es/articles/ecommerce-kvkk-cookie-policy-compliance", permanent: true },
      { source: "/es/articles/evlilik-yoluyla-turk-vatandasligi", destination: "/es/articles/turkish-citizenship-through-marriage", permanent: true },
      { source: "/es/articles/ihtiyac-nedeniyle-tahliye-tbk-350", destination: "/es/articles/eviction-landlord-need-turkey", permanent: true },
      { source: "/es/articles/iki-hakli-ihtar-kira-odemeyen-kiraciyi-tahliye", destination: "/es/articles/tenant-non-payment-eviction-two-notice-turkey", permanent: true },
      { source: "/es/articles/isyeri-kira-sozlesmesi", destination: "/es/articles/commercial-lease-turkey", permanent: true },
      { source: "/es/articles/kidem-ihbar-tazminati-yabancilar-hesaplama", destination: "/es/articles/severance-notice-pay-foreigners-calculation", permanent: true },
      { source: "/es/articles/kira-artisi-siniri-tbk-344", destination: "/es/articles/rent-increase-cap-turkey", permanent: true },
      { source: "/es/articles/kira-depozito-guvence-bedeli", destination: "/es/articles/security-deposit-rental-turkey", permanent: true },
      { source: "/es/articles/kira-tespiti-davasi", destination: "/es/articles/rent-determination-lawsuit-turkey", permanent: true },
      { source: "/es/articles/kvkk-uyumu-turkiye-veri-koruma-yukumlulukleri", destination: "/es/articles/kvkk-compliance-turkey-data-protection", permanent: true },
      { source: "/es/articles/miras-reddi-sartlar-sure", destination: "/es/articles/inheritance-rejection-conditions-period", permanent: true },
      { source: "/es/articles/mobbing-hukuki-yaptirim", destination: "/es/articles/mobbing-workplace-harassment-legal-remedies", permanent: true },
      { source: "/es/articles/nafaka-turleri-yabanci-muvekkiller", destination: "/es/articles/alimony-types-foreign-clients-turkey", permanent: true },
      { source: "/es/articles/ogrenci-ikamet-izninden-calisma-izni-gecis", destination: "/es/articles/student-to-work-permit-transition-turkey", permanent: true },
      { source: "/es/articles/oturma-izni-iptali-hukuki-yollar", destination: "/es/articles/residence-permit-cancellation-legal-routes", permanent: true },
      { source: "/es/articles/sahte-tapu-dolandiriciligina-karsi-korunma", destination: "/es/articles/protecting-against-fraud-property-purchase-turkey", permanent: true },
      { source: "/es/articles/sinir-disi-karari-itiraz-hak-yollari", destination: "/es/articles/deportation-order-appeal-turkey", permanent: true },
      { source: "/es/articles/sirket-devir-birlesme-hukuki-surec", destination: "/es/articles/company-merger-acquisition-legal-process", permanent: true },
      { source: "/es/articles/sosyal-medya-iftirasi-hukuki-yaptirim", destination: "/es/articles/social-media-defamation-legal-remedies", permanent: true },
      { source: "/es/articles/tahdit-kodu-sorgulama-kaldirma", destination: "/es/articles/restriction-code-check-removal-foreigners", permanent: true },
      { source: "/es/articles/tapu-devri-sirasinda-dikkat-edilmesi-gerekenler", destination: "/es/articles/title-deed-transfer-checklist-foreign-buyers", permanent: true },
      { source: "/es/articles/ticari-sozlesmelerde-sikca-yapilan-hatalar", destination: "/es/articles/common-mistakes-commercial-contracts-turkey", permanent: true },
      { source: "/es/articles/trafik-kazasinda-ceza-sorumlulugu-yabanci-surucu", destination: "/es/articles/traffic-accident-criminal-liability-foreign-drivers", permanent: true },
      { source: "/es/articles/turk-vatandasligi-basvuru-reddi-itiraz", destination: "/es/articles/turkish-citizenship-application-rejection-appeal", permanent: true },
      { source: "/es/articles/turk-vatandasligi-cifte-vatandaslik-statusu", destination: "/es/articles/turkish-dual-citizenship-status", permanent: true },
      { source: "/es/articles/turkiye-kisa-donem-ikamet-izni-basvurusu-rehberi", destination: "/es/articles/short-term-residence-permit-turkey-guide", permanent: true },
      { source: "/es/articles/turkiyede-mulku-olan-yabancilarin-miras-hukuku", destination: "/es/articles/foreigners-property-turkey-inheritance-law", permanent: true },
      { source: "/es/articles/turkiyede-yabanci-calisanin-isten-cikarilmasi", destination: "/es/articles/foreign-employee-termination-turkey", permanent: true },
      { source: "/es/articles/uluslararasi-bosanma-turkiyede-tanima-tenfiz", destination: "/es/articles/international-divorce-recognition-enforcement-turkey", permanent: true },
      { source: "/es/articles/uluslararasi-cocuk-kacirma-lahey-sozlesmesi", destination: "/es/articles/international-child-abduction-hague-convention", permanent: true },
      { source: "/es/articles/uyusturucu-suclarinda-savunma-stratejileri", destination: "/es/articles/narcotics-offences-defence-strategies-turkey", permanent: true },
      { source: "/es/articles/uzaktan-calisan-yabanci-isci-haklari", destination: "/es/articles/remote-foreign-workers-rights-turkey", permanent: true },
      { source: "/es/articles/vasiyetname-duzenleme-yabancilar-icin", destination: "/es/articles/will-drafting-foreigners-turkey", permanent: true },
      { source: "/es/articles/velayet-davalarinda-yabancilarin-haklari", destination: "/es/articles/custody-rights-foreign-clients-turkey", permanent: true },
      { source: "/es/articles/veraset-ilami-yabanci-mirasci-rehber", destination: "/es/articles/certificate-of-inheritance-foreign-heirs", permanent: true },
      { source: "/es/articles/vize-reddi-iptal-davasi", destination: "/es/articles/visa-denial-cancellation-lawsuit-turkey", permanent: true },
      { source: "/es/articles/yabanci-es-cocuk-icin-turk-vatandasligi", destination: "/es/articles/turkish-citizenship-for-spouse-and-children", permanent: true },
      { source: "/es/articles/yabanci-eslerin-bosanmasinda-mal-paylasimi", destination: "/es/articles/property-division-foreign-spouses-divorce-turkey", permanent: true },
      { source: "/es/articles/yabanci-olarak-turkiye-daire-almak-hukuki-rehber", destination: "/es/articles/buying-property-in-turkey-foreigner-guide", permanent: true },
      { source: "/es/articles/yabanci-sermaye-turkiyede-ortaklik-kurma", destination: "/es/articles/foreign-capital-partnership-turkey", permanent: true },
      { source: "/es/articles/yabanci-vasiyetnamesi-turkiyede-tanima", destination: "/es/articles/foreign-will-recognition-turkey", permanent: true },
      { source: "/es/articles/yabanci-yatirimci-turkiyede-sirket-kurma", destination: "/es/articles/foreign-investor-company-formation-turkey", permanent: true },
      { source: "/es/articles/yabancilar-icin-idare-mahkemesi-surecleri", destination: "/es/articles/administrative-court-procedure-foreigners", permanent: true },
      { source: "/es/articles/yabancilar-icin-turkiye-ceza-davasi-sureci", destination: "/es/articles/criminal-procedure-foreigners-turkey", permanent: true },
      { source: "/es/articles/yabancilar-icin-tutuklama-adli-kontrol", destination: "/es/articles/detention-judicial-control-foreigners-turkey", permanent: true },
      { source: "/es/articles/yapay-zeka-turk-hukuku-duzenleme-cercevesi", destination: "/es/articles/artificial-intelligence-turkish-law-framework", permanent: true },
      { source: "/es/articles/yatirim-amacli-konut-alimi-vergi-hukuki-yukumluluk", destination: "/es/articles/investment-property-turkey-tax-legal-obligations", permanent: true },
      { source: "/es/articles/yatirim-yoluyla-turk-vatandasligi-tam-rehber", destination: "/es/articles/turkish-citizenship-by-investment-full-guide", permanent: true },
      { source: "/es/articles/yazilim-lisans-sozlesmelerinde-hukuki-riskler", destination: "/es/articles/software-license-agreements-legal-risks", permanent: true },

      // ── EN: Türkçe-slug → İngilizce-slug ─────────────────────────────────────
      { source: "/en/articles/aile-ikamet-izni-turk-vatandasi-es", destination: "/en/articles/family-residence-permit-spouse-turkish-citizen", permanent: true },
      { source: "/en/articles/anonim-sirket-vs-limited-sirket-secim", destination: "/en/articles/jsc-vs-llc-which-to-choose-turkey", permanent: true },
      { source: "/en/articles/antalya-kira-sozlesmesi-haklar-yukumlulukler", destination: "/en/articles/antalya-rental-agreement-rights-obligations", permanent: true },
      { source: "/en/articles/calisma-izni-iptali-is-sozlesmesi-sona-ermesi", destination: "/en/articles/work-permit-cancellation-employment-contract-end", permanent: true },
      { source: "/en/articles/calisma-izni-reddi-itiraz-yollari", destination: "/en/articles/work-permit-denial-appeal-turkey", permanent: true },
      { source: "/en/articles/dolandiricilik-magdurlari-icin-hukuki-yollar", destination: "/en/articles/fraud-victims-foreigners-legal-remedies", permanent: true },
      { source: "/en/articles/eticaret-kvkk-cerez-politikasi", destination: "/en/articles/ecommerce-kvkk-cookie-policy-compliance", permanent: true },
      { source: "/en/articles/evlilik-yoluyla-turk-vatandasligi", destination: "/en/articles/turkish-citizenship-through-marriage", permanent: true },
      { source: "/en/articles/ihtiyac-nedeniyle-tahliye-tbk-350", destination: "/en/articles/eviction-landlord-need-turkey", permanent: true },
      { source: "/en/articles/iki-hakli-ihtar-kira-odemeyen-kiraciyi-tahliye", destination: "/en/articles/tenant-non-payment-eviction-two-notice-turkey", permanent: true },
      { source: "/en/articles/isyeri-kira-sozlesmesi", destination: "/en/articles/commercial-lease-turkey", permanent: true },
      { source: "/en/articles/kidem-ihbar-tazminati-yabancilar-hesaplama", destination: "/en/articles/severance-notice-pay-foreigners-calculation", permanent: true },
      { source: "/en/articles/kira-artisi-siniri-tbk-344", destination: "/en/articles/rent-increase-cap-turkey", permanent: true },
      { source: "/en/articles/kira-depozito-guvence-bedeli", destination: "/en/articles/security-deposit-rental-turkey", permanent: true },
      { source: "/en/articles/kira-tespiti-davasi", destination: "/en/articles/rent-determination-lawsuit-turkey", permanent: true },
      { source: "/en/articles/kvkk-uyumu-turkiye-veri-koruma-yukumlulukleri", destination: "/en/articles/kvkk-compliance-turkey-data-protection", permanent: true },
      { source: "/en/articles/miras-reddi-sartlar-sure", destination: "/en/articles/inheritance-rejection-conditions-period", permanent: true },
      { source: "/en/articles/mobbing-hukuki-yaptirim", destination: "/en/articles/mobbing-workplace-harassment-legal-remedies", permanent: true },
      { source: "/en/articles/nafaka-turleri-yabanci-muvekkiller", destination: "/en/articles/alimony-types-foreign-clients-turkey", permanent: true },
      { source: "/en/articles/ogrenci-ikamet-izninden-calisma-izni-gecis", destination: "/en/articles/student-to-work-permit-transition-turkey", permanent: true },
      { source: "/en/articles/oturma-izni-iptali-hukuki-yollar", destination: "/en/articles/residence-permit-cancellation-legal-routes", permanent: true },
      { source: "/en/articles/sahte-tapu-dolandiriciligina-karsi-korunma", destination: "/en/articles/protecting-against-fraud-property-purchase-turkey", permanent: true },
      { source: "/en/articles/sosyal-medya-iftirasi-hukuki-yaptirim", destination: "/en/articles/social-media-defamation-legal-remedies", permanent: true },
      { source: "/en/articles/tapu-devri-sirasinda-dikkat-edilmesi-gerekenler", destination: "/en/articles/title-deed-transfer-checklist-foreign-buyers", permanent: true },
      { source: "/en/articles/ticari-sozlesmelerde-sikca-yapilan-hatalar", destination: "/en/articles/common-mistakes-commercial-contracts-turkey", permanent: true },
      { source: "/en/articles/trafik-kazasinda-ceza-sorumlulugu-yabanci-surucu", destination: "/en/articles/traffic-accident-criminal-liability-foreign-drivers", permanent: true },
      { source: "/en/articles/turk-vatandasligi-basvuru-reddi-itiraz", destination: "/en/articles/turkish-citizenship-application-rejection-appeal", permanent: true },
      { source: "/en/articles/turk-vatandasligi-cifte-vatandaslik-statusu", destination: "/en/articles/turkish-dual-citizenship-status", permanent: true },
      { source: "/en/articles/turkiye-kisa-donem-ikamet-izni-basvurusu-rehberi", destination: "/en/articles/short-term-residence-permit-turkey-guide", permanent: true },
      { source: "/en/articles/turkiyede-mulku-olan-yabancilarin-miras-hukuku", destination: "/en/articles/foreigners-property-turkey-inheritance-law", permanent: true },
      { source: "/en/articles/turkiyede-yabanci-calisanin-isten-cikarilmasi", destination: "/en/articles/foreign-employee-termination-turkey", permanent: true },
      { source: "/en/articles/uluslararasi-bosanma-turkiyede-tanima-tenfiz", destination: "/en/articles/international-divorce-recognition-enforcement-turkey", permanent: true },
      { source: "/en/articles/uluslararasi-cocuk-kacirma-lahey-sozlesmesi", destination: "/en/articles/international-child-abduction-hague-convention", permanent: true },
      { source: "/en/articles/uyusturucu-suclarinda-savunma-stratejileri", destination: "/en/articles/narcotics-offences-defence-strategies-turkey", permanent: true },
      { source: "/en/articles/uzaktan-calisan-yabanci-isci-haklari", destination: "/en/articles/remote-foreign-workers-rights-turkey", permanent: true },
      { source: "/en/articles/vasiyetname-duzenleme-yabancilar-icin", destination: "/en/articles/will-drafting-foreigners-turkey", permanent: true },
      { source: "/en/articles/velayet-davalarinda-yabancilarin-haklari", destination: "/en/articles/custody-rights-foreign-clients-turkey", permanent: true },
      { source: "/en/articles/veraset-ilami-yabanci-mirasci-rehber", destination: "/en/articles/certificate-of-inheritance-foreign-heirs", permanent: true },
      { source: "/en/articles/vize-reddi-iptal-davasi", destination: "/en/articles/visa-denial-cancellation-lawsuit-turkey", permanent: true },
      { source: "/en/articles/yabanci-es-cocuk-icin-turk-vatandasligi", destination: "/en/articles/turkish-citizenship-for-spouse-and-children", permanent: true },
      { source: "/en/articles/yabanci-eslerin-bosanmasinda-mal-paylasimi", destination: "/en/articles/property-division-foreign-spouses-divorce-turkey", permanent: true },
      { source: "/en/articles/yabanci-olarak-turkiye-daire-almak-hukuki-rehber", destination: "/en/articles/buying-property-in-turkey-foreigner-guide", permanent: true },
      { source: "/en/articles/yabanci-vasiyetnamesi-turkiyede-tanima", destination: "/en/articles/foreign-will-recognition-turkey", permanent: true },
      { source: "/en/articles/yabanci-yatirimci-turkiyede-sirket-kurma", destination: "/en/articles/foreign-investor-company-formation-turkey", permanent: true },
      { source: "/en/articles/yabancilar-icin-idare-mahkemesi-surecleri", destination: "/en/articles/administrative-court-procedure-foreigners", permanent: true },
      { source: "/en/articles/yabancilar-icin-turkiye-ceza-davasi-sureci", destination: "/en/articles/criminal-procedure-foreigners-turkey", permanent: true },
      { source: "/en/articles/yabancilar-icin-tutuklama-adli-kontrol", destination: "/en/articles/detention-judicial-control-foreigners-turkey", permanent: true },
      { source: "/en/articles/yapay-zeka-turk-hukuku-duzenleme-cercevesi", destination: "/en/articles/artificial-intelligence-turkish-law-framework", permanent: true },
      { source: "/en/articles/yatirim-amacli-konut-alimi-vergi-hukuki-yukumluluk", destination: "/en/articles/investment-property-turkey-tax-legal-obligations", permanent: true },
      { source: "/en/articles/yatirim-yoluyla-turk-vatandasligi-tam-rehber", destination: "/en/articles/turkish-citizenship-by-investment-full-guide", permanent: true },

      // ── FR: Türkçe-slug → İngilizce-slug (31 Mayıs QA silme işlemi sonrası) ──
      // QA workflow c8b6a6f commit'inde 56 FR Türkçe-slug dosyası "spurious" olarak
      // yanlışlıkla silindi. Google bu URL'leri indexlemişti; redirect ile 404→301.
      { source: "/fr/articles/aile-ikamet-izni-turk-vatandasi-es", destination: "/fr/articles/family-residence-permit-spouse-turkish-citizen", permanent: true },
      { source: "/fr/articles/anonim-sirket-vs-limited-sirket-secim", destination: "/fr/articles/jsc-vs-llc-which-to-choose-turkey", permanent: true },
      { source: "/fr/articles/antalya-kira-sozlesmesi-haklar-yukumlulukler", destination: "/fr/articles/antalya-rental-agreement-rights-obligations", permanent: true },
      { source: "/fr/articles/belediye-cezalarina-itiraz-yabancilar", destination: "/fr/articles/municipality-fines-objection-foreigners", permanent: true },
      { source: "/fr/articles/calisma-izni-iptali-is-sozlesmesi-sona-ermesi", destination: "/fr/articles/work-permit-cancellation-employment-contract-end", permanent: true },
      { source: "/fr/articles/calisma-izni-reddi-itiraz-yollari", destination: "/fr/articles/work-permit-denial-appeal-turkey", permanent: true },
      { source: "/fr/articles/dolandiricilik-magdurlari-icin-hukuki-yollar", destination: "/fr/articles/fraud-victims-foreigners-legal-remedies", permanent: true },
      { source: "/fr/articles/eticaret-kvkk-cerez-politikasi", destination: "/fr/articles/ecommerce-kvkk-cookie-policy-compliance", permanent: true },
      { source: "/fr/articles/evlilik-yoluyla-turk-vatandasligi", destination: "/fr/articles/turkish-citizenship-through-marriage", permanent: true },
      { source: "/fr/articles/ihtiyac-nedeniyle-tahliye-tbk-350", destination: "/fr/articles/eviction-landlord-need-turkey", permanent: true },
      { source: "/fr/articles/iki-hakli-ihtar-kira-odemeyen-kiraciyi-tahliye", destination: "/fr/articles/tenant-non-payment-eviction-two-notice-turkey", permanent: true },
      { source: "/fr/articles/isyeri-kira-sozlesmesi", destination: "/fr/articles/commercial-lease-turkey", permanent: true },
      { source: "/fr/articles/kidem-ihbar-tazminati-yabancilar-hesaplama", destination: "/fr/articles/severance-notice-pay-foreigners-calculation", permanent: true },
      { source: "/fr/articles/kira-artisi-siniri-tbk-344", destination: "/fr/articles/rent-increase-cap-turkey", permanent: true },
      { source: "/fr/articles/kira-depozito-guvence-bedeli", destination: "/fr/articles/security-deposit-rental-turkey", permanent: true },
      { source: "/fr/articles/kira-tespiti-davasi", destination: "/fr/articles/rent-determination-lawsuit-turkey", permanent: true },
      { source: "/fr/articles/kvkk-uyumu-turkiye-veri-koruma-yukumlulukleri", destination: "/fr/articles/kvkk-compliance-turkey-data-protection", permanent: true },
      { source: "/fr/articles/miras-reddi-sartlar-sure", destination: "/fr/articles/inheritance-rejection-conditions-period", permanent: true },
      { source: "/fr/articles/mobbing-hukuki-yaptirim", destination: "/fr/articles/mobbing-workplace-harassment-legal-remedies", permanent: true },
      { source: "/fr/articles/nafaka-turleri-yabanci-muvekkiller", destination: "/fr/articles/alimony-types-foreign-clients-turkey", permanent: true },
      { source: "/fr/articles/ogrenci-ikamet-izninden-calisma-izni-gecis", destination: "/fr/articles/student-to-work-permit-transition-turkey", permanent: true },
      { source: "/fr/articles/oturma-izni-iptali-hukuki-yollar", destination: "/fr/articles/residence-permit-cancellation-legal-routes", permanent: true },
      { source: "/fr/articles/sahte-tapu-dolandiriciligina-karsi-korunma", destination: "/fr/articles/protecting-against-fraud-property-purchase-turkey", permanent: true },
      { source: "/fr/articles/sinir-disi-karari-itiraz-hak-yollari", destination: "/fr/articles/deportation-order-appeal-turkey", permanent: true },
      { source: "/fr/articles/sirket-devir-birlesme-hukuki-surec", destination: "/fr/articles/company-merger-acquisition-legal-process", permanent: true },
      { source: "/fr/articles/sosyal-medya-iftirasi-hukuki-yaptirim", destination: "/fr/articles/social-media-defamation-legal-remedies", permanent: true },
      { source: "/fr/articles/tahdit-kodu-sorgulama-kaldirma", destination: "/fr/articles/restriction-code-check-removal-foreigners", permanent: true },
      { source: "/fr/articles/tapu-devri-sirasinda-dikkat-edilmesi-gerekenler", destination: "/fr/articles/title-deed-transfer-checklist-foreign-buyers", permanent: true },
      { source: "/fr/articles/ticari-sozlesmelerde-sikca-yapilan-hatalar", destination: "/fr/articles/common-mistakes-commercial-contracts-turkey", permanent: true },
      { source: "/fr/articles/trafik-kazasinda-ceza-sorumlulugu-yabanci-surucu", destination: "/fr/articles/traffic-accident-criminal-liability-foreign-drivers", permanent: true },
      { source: "/fr/articles/turk-vatandasligi-basvuru-reddi-itiraz", destination: "/fr/articles/turkish-citizenship-application-rejection-appeal", permanent: true },
      { source: "/fr/articles/turk-vatandasligi-cifte-vatandaslik-statusu", destination: "/fr/articles/turkish-dual-citizenship-status", permanent: true },
      { source: "/fr/articles/turkiye-kisa-donem-ikamet-izni-basvurusu-rehberi", destination: "/fr/articles/short-term-residence-permit-turkey-guide", permanent: true },
      { source: "/fr/articles/turkiyede-mulku-olan-yabancilarin-miras-hukuku", destination: "/fr/articles/foreigners-property-turkey-inheritance-law", permanent: true },
      { source: "/fr/articles/turkiyede-yabanci-calisanin-isten-cikarilmasi", destination: "/fr/articles/foreign-employee-termination-turkey", permanent: true },
      { source: "/fr/articles/uluslararasi-bosanma-turkiyede-tanima-tenfiz", destination: "/fr/articles/international-divorce-recognition-enforcement-turkey", permanent: true },
      { source: "/fr/articles/uluslararasi-cocuk-kacirma-lahey-sozlesmesi", destination: "/fr/articles/international-child-abduction-hague-convention", permanent: true },
      { source: "/fr/articles/uyusturucu-suclarinda-savunma-stratejileri", destination: "/fr/articles/narcotics-offences-defence-strategies-turkey", permanent: true },
      { source: "/fr/articles/uzaktan-calisan-yabanci-isci-haklari", destination: "/fr/articles/remote-foreign-workers-rights-turkey", permanent: true },
      { source: "/fr/articles/vasiyetname-duzenleme-yabancilar-icin", destination: "/fr/articles/will-drafting-foreigners-turkey", permanent: true },
      { source: "/fr/articles/velayet-davalarinda-yabancilarin-haklari", destination: "/fr/articles/custody-rights-foreign-clients-turkey", permanent: true },
      { source: "/fr/articles/veraset-ilami-yabanci-mirasci-rehber", destination: "/fr/articles/certificate-of-inheritance-foreign-heirs", permanent: true },
      { source: "/fr/articles/vize-reddi-iptal-davasi", destination: "/fr/articles/visa-denial-cancellation-lawsuit-turkey", permanent: true },
      { source: "/fr/articles/yabanci-es-cocuk-icin-turk-vatandasligi", destination: "/fr/articles/turkish-citizenship-for-spouse-and-children", permanent: true },
      { source: "/fr/articles/yabanci-eslerin-bosanmasinda-mal-paylasimi", destination: "/fr/articles/property-division-foreign-spouses-divorce-turkey", permanent: true },
      { source: "/fr/articles/yabanci-olarak-turkiye-daire-almak-hukuki-rehber", destination: "/fr/articles/buying-property-in-turkey-foreigner-guide", permanent: true },
      { source: "/fr/articles/yabanci-sermaye-turkiyede-ortaklik-kurma", destination: "/fr/articles/foreign-capital-partnership-turkey", permanent: true },
      { source: "/fr/articles/yabanci-vasiyetnamesi-turkiyede-tanima", destination: "/fr/articles/foreign-will-recognition-turkey", permanent: true },
      { source: "/fr/articles/yabanci-yatirimci-turkiyede-sirket-kurma", destination: "/fr/articles/foreign-investor-company-formation-turkey", permanent: true },
      { source: "/fr/articles/yabancilar-icin-idare-mahkemesi-surecleri", destination: "/fr/articles/administrative-court-procedure-foreigners", permanent: true },
      { source: "/fr/articles/yabancilar-icin-turkiye-ceza-davasi-sureci", destination: "/fr/articles/criminal-procedure-foreigners-turkey", permanent: true },
      { source: "/fr/articles/yabancilar-icin-tutuklama-adli-kontrol", destination: "/fr/articles/detention-judicial-control-foreigners-turkey", permanent: true },
      { source: "/fr/articles/yapay-zeka-turk-hukuku-duzenleme-cercevesi", destination: "/fr/articles/artificial-intelligence-turkish-law-framework", permanent: true },
      { source: "/fr/articles/yatirim-amacli-konut-alimi-vergi-hukuki-yukumluluk", destination: "/fr/articles/investment-property-turkey-tax-legal-obligations", permanent: true },
      { source: "/fr/articles/yatirim-yoluyla-turk-vatandasligi-tam-rehber", destination: "/fr/articles/turkish-citizenship-by-investment-full-guide", permanent: true },
      { source: "/fr/articles/yazilim-lisans-sozlesmelerinde-hukuki-riskler", destination: "/fr/articles/software-license-agreements-legal-risks", permanent: true },

      // ── Locale prefix'siz /articles/ → /tr/articles/ (catch-all) ───────────
      { source: "/articles/:slug*", destination: "/tr/articles/:slug*", permanent: true },
      { source: "/legal-news/:slug*", destination: "/tr/legal-news/:slug*", permanent: true },

      // ── Günlük haber cron: silinmiş tarihli sayfalar → legal-news index ────
      { source: "/:locale(tr|en|de|ru|ar|es|fr)/legal-news/2026-06-01-hukuki-haberler", destination: "/:locale/legal-news", permanent: false },
      { source: "/:locale(tr|en|de|ru|ar|es|fr)/legal-news/2026-06-01-legal-news", destination: "/:locale/legal-news", permanent: false },

      // ── Legal-news: çapraz slug suffix düzeltme ────────────────────────────────
      // TR-olmayan locale'de hukuki-haberler suffix gelirse → locale legal-news index
      { source: "/:locale(en|de|ru|ar|es|fr)/legal-news/:date(\\d{4}-\\d{2}-\\d{2})-hukuki-haberler", destination: "/:locale/legal-news", permanent: true },
      // TR locale'de legal-news suffix gelirse → TR legal-news index
      { source: "/tr/legal-news/:date(\\d{4}-\\d{2}-\\d{2})-legal-news", destination: "/tr/legal-news", permanent: true },

      // ── TR: İngilizce-slug → Türkçe-slug (TR locale yalnızca TR slug kullanır) ─
      { source: "/tr/articles/family-residence-permit-spouse-turkish-citizen", destination: "/tr/articles/aile-ikamet-izni-turk-vatandasi-es", permanent: true },
      { source: "/tr/articles/jsc-vs-llc-which-to-choose-turkey", destination: "/tr/articles/anonim-sirket-vs-limited-sirket-secim", permanent: true },
      { source: "/tr/articles/antalya-rental-agreement-rights-obligations", destination: "/tr/articles/antalya-kira-sozlesmesi-haklar-yukumlulukler", permanent: true },
      { source: "/tr/articles/municipality-fines-objection-foreigners", destination: "/tr/articles/belediye-cezalarina-itiraz-yabancilar", permanent: true },
      { source: "/tr/articles/work-permit-cancellation-employment-contract-end", destination: "/tr/articles/calisma-izni-iptali-is-sozlesmesi-sona-ermesi", permanent: true },
      { source: "/tr/articles/work-permit-denial-appeal-turkey", destination: "/tr/articles/calisma-izni-reddi-itiraz-yollari", permanent: true },
      { source: "/tr/articles/fraud-victims-foreigners-legal-remedies", destination: "/tr/articles/dolandiricilik-magdurlari-icin-hukuki-yollar", permanent: true },
      { source: "/tr/articles/ecommerce-kvkk-cookie-policy-compliance", destination: "/tr/articles/eticaret-kvkk-cerez-politikasi", permanent: true },
      { source: "/tr/articles/turkish-citizenship-through-marriage", destination: "/tr/articles/evlilik-yoluyla-turk-vatandasligi", permanent: true },
      { source: "/tr/articles/eviction-landlord-need-turkey", destination: "/tr/articles/ihtiyac-nedeniyle-tahliye-tbk-350", permanent: true },
      { source: "/tr/articles/tenant-non-payment-eviction-two-notice-turkey", destination: "/tr/articles/iki-hakli-ihtar-kira-odemeyen-kiraciyi-tahliye", permanent: true },
      { source: "/tr/articles/commercial-lease-turkey", destination: "/tr/articles/isyeri-kira-sozlesmesi", permanent: true },
      { source: "/tr/articles/severance-notice-pay-foreigners-calculation", destination: "/tr/articles/kidem-ihbar-tazminati-yabancilar-hesaplama", permanent: true },
      { source: "/tr/articles/rent-increase-cap-turkey", destination: "/tr/articles/kira-artisi-siniri-tbk-344", permanent: true },
      { source: "/tr/articles/security-deposit-rental-turkey", destination: "/tr/articles/kira-depozito-guvence-bedeli", permanent: true },
      { source: "/tr/articles/rent-determination-lawsuit-turkey", destination: "/tr/articles/kira-tespiti-davasi", permanent: true },
      { source: "/tr/articles/kvkk-compliance-turkey-data-protection", destination: "/tr/articles/kvkk-uyumu-turkiye-veri-koruma-yukumlulukleri", permanent: true },
      { source: "/tr/articles/inheritance-rejection-conditions-period", destination: "/tr/articles/miras-reddi-sartlar-sure", permanent: true },
      { source: "/tr/articles/mobbing-workplace-harassment-legal-remedies", destination: "/tr/articles/mobbing-hukuki-yaptirim", permanent: true },
      { source: "/tr/articles/alimony-types-foreign-clients-turkey", destination: "/tr/articles/nafaka-turleri-yabanci-muvekkiller", permanent: true },
      { source: "/tr/articles/student-to-work-permit-transition-turkey", destination: "/tr/articles/ogrenci-ikamet-izninden-calisma-izni-gecis", permanent: true },
      { source: "/tr/articles/residence-permit-cancellation-legal-routes", destination: "/tr/articles/oturma-izni-iptali-hukuki-yollar", permanent: true },
      { source: "/tr/articles/protecting-against-fraud-property-purchase-turkey", destination: "/tr/articles/sahte-tapu-dolandiriciligina-karsi-korunma", permanent: true },
      { source: "/tr/articles/deportation-order-appeal-turkey", destination: "/tr/articles/sinir-disi-karari-itiraz-hak-yollari", permanent: true },
      { source: "/tr/articles/company-merger-acquisition-legal-process", destination: "/tr/articles/sirket-devir-birlesme-hukuki-surec", permanent: true },
      { source: "/tr/articles/social-media-defamation-legal-remedies", destination: "/tr/articles/sosyal-medya-iftirasi-hukuki-yaptirim", permanent: true },
      { source: "/tr/articles/restriction-code-check-removal-foreigners", destination: "/tr/articles/tahdit-kodu-sorgulama-kaldirma", permanent: true },
      { source: "/tr/articles/title-deed-transfer-checklist-foreign-buyers", destination: "/tr/articles/tapu-devri-sirasinda-dikkat-edilmesi-gerekenler", permanent: true },
      { source: "/tr/articles/common-mistakes-commercial-contracts-turkey", destination: "/tr/articles/ticari-sozlesmelerde-sikca-yapilan-hatalar", permanent: true },
      { source: "/tr/articles/traffic-accident-criminal-liability-foreign-drivers", destination: "/tr/articles/trafik-kazasinda-ceza-sorumlulugu-yabanci-surucu", permanent: true },
      { source: "/tr/articles/turkish-citizenship-application-rejection-appeal", destination: "/tr/articles/turk-vatandasligi-basvuru-reddi-itiraz", permanent: true },
      { source: "/tr/articles/turkish-dual-citizenship-status", destination: "/tr/articles/turk-vatandasligi-cifte-vatandaslik-statusu", permanent: true },
      { source: "/tr/articles/short-term-residence-permit-turkey-guide", destination: "/tr/articles/turkiye-kisa-donem-ikamet-izni-basvurusu-rehberi", permanent: true },
      { source: "/tr/articles/foreigners-property-turkey-inheritance-law", destination: "/tr/articles/turkiyede-mulku-olan-yabancilarin-miras-hukuku", permanent: true },
      { source: "/tr/articles/foreign-employee-termination-turkey", destination: "/tr/articles/turkiyede-yabanci-calisanin-isten-cikarilmasi", permanent: true },
      { source: "/tr/articles/international-divorce-recognition-enforcement-turkey", destination: "/tr/articles/uluslararasi-bosanma-turkiyede-tanima-tenfiz", permanent: true },
      { source: "/tr/articles/international-child-abduction-hague-convention", destination: "/tr/articles/uluslararasi-cocuk-kacirma-lahey-sozlesmesi", permanent: true },
      { source: "/tr/articles/narcotics-offences-defence-strategies-turkey", destination: "/tr/articles/uyusturucu-suclarinda-savunma-stratejileri", permanent: true },
      { source: "/tr/articles/remote-foreign-workers-rights-turkey", destination: "/tr/articles/uzaktan-calisan-yabanci-isci-haklari", permanent: true },
      { source: "/tr/articles/will-drafting-foreigners-turkey", destination: "/tr/articles/vasiyetname-duzenleme-yabancilar-icin", permanent: true },
      { source: "/tr/articles/custody-rights-foreign-clients-turkey", destination: "/tr/articles/velayet-davalarinda-yabancilarin-haklari", permanent: true },
      { source: "/tr/articles/certificate-of-inheritance-foreign-heirs", destination: "/tr/articles/veraset-ilami-yabanci-mirasci-rehber", permanent: true },
      { source: "/tr/articles/visa-denial-cancellation-lawsuit-turkey", destination: "/tr/articles/vize-reddi-iptal-davasi", permanent: true },
      { source: "/tr/articles/turkish-citizenship-for-spouse-and-children", destination: "/tr/articles/yabanci-es-cocuk-icin-turk-vatandasligi", permanent: true },
      { source: "/tr/articles/property-division-foreign-spouses-divorce-turkey", destination: "/tr/articles/yabanci-eslerin-bosanmasinda-mal-paylasimi", permanent: true },
      { source: "/tr/articles/buying-property-in-turkey-foreigner-guide", destination: "/tr/articles/yabanci-olarak-turkiye-daire-almak-hukuki-rehber", permanent: true },
      { source: "/tr/articles/foreign-capital-partnership-turkey", destination: "/tr/articles/yabanci-sermaye-turkiyede-ortaklik-kurma", permanent: true },
      { source: "/tr/articles/foreign-will-recognition-turkey", destination: "/tr/articles/yabanci-vasiyetnamesi-turkiyede-tanima", permanent: true },
      { source: "/tr/articles/foreign-investor-company-formation-turkey", destination: "/tr/articles/yabanci-yatirimci-turkiyede-sirket-kurma", permanent: true },
      { source: "/tr/articles/administrative-court-procedure-foreigners", destination: "/tr/articles/yabancilar-icin-idare-mahkemesi-surecleri", permanent: true },
      { source: "/tr/articles/criminal-procedure-foreigners-turkey", destination: "/tr/articles/yabancilar-icin-turkiye-ceza-davasi-sureci", permanent: true },
      { source: "/tr/articles/detention-judicial-control-foreigners-turkey", destination: "/tr/articles/yabancilar-icin-tutuklama-adli-kontrol", permanent: true },
      { source: "/tr/articles/artificial-intelligence-turkish-law-framework", destination: "/tr/articles/yapay-zeka-turk-hukuku-duzenleme-cercevesi", permanent: true },
      { source: "/tr/articles/investment-property-turkey-tax-legal-obligations", destination: "/tr/articles/yatirim-amacli-konut-alimi-vergi-hukuki-yukumluluk", permanent: true },
      { source: "/tr/articles/turkish-citizenship-by-investment-full-guide", destination: "/tr/articles/yatirim-yoluyla-turk-vatandasligi-tam-rehber", permanent: true },
      { source: "/tr/articles/software-license-agreements-legal-risks", destination: "/tr/articles/yazilim-lisans-sozlesmelerinde-hukuki-riskler", permanent: true },

      // ── Silinen welcome sayfaları (28 Nisan'da kaldırıldı) ───────────────────
      { source: "/tr/articles/welcome", destination: "/tr/articles", permanent: false },
      { source: "/en/articles/welcome", destination: "/en/articles", permanent: false },

      // ── Trailing slash → canonical (Next.js 308 yerine 301) ─────────────────
      // GSC bu URL'leri "Yönlendirmeli sayfa" olarak görüyor.
      { source: "/tr/", destination: "/tr", permanent: true },
      { source: "/en/", destination: "/en", permanent: true },
      { source: "/de/", destination: "/de", permanent: true },
      { source: "/ru/", destination: "/ru", permanent: true },
      { source: "/ar/", destination: "/ar", permanent: true },
      { source: "/es/", destination: "/es", permanent: true },
      { source: "/fr/", destination: "/fr", permanent: true },
    ];
  },
};

export default withNextIntl(nextConfig);

import('@opennextjs/cloudflare').then(m => m.initOpenNextCloudflareForDev());
